name = "MarkovRandomFields"
uuid = "89aeb94b-8fe9-403e-922a-14510fb125d2"
authors = ["stecrotti <sky_96@live.it>"]
version = "0.1.0"

[deps]
IndexedFactorGraphs = "edf0a622-c16b-410a-a162-e53dc16a76ae"
IndexedGraphs = "8a731c18-cfb7-4915-927e-cc26b56b67cd"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
LogarithmicNumbers = "aa2f6b4e-9042-5d33-9679-40d3a6b85899"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
IndexedFactorGraphs = "0.2.0"
IndexedGraphs = "0.6.1"
InvertedIndices = "1.3.1"
LinearAlgebra = "1.1"
LogExpFunctions = "0.3.29"
LogarithmicNumbers = "1.4.1"
Random = "1.11"
StatsBase = "0.34.5"
julia = "1.11"
